### ISSUE TITLE
Create 'home' page 

### ISSUE THREAD

**Issue by hanEck** [vim/website_next_generation#11]
-Creating single page collection for 'home' page in Strapi
-Create frontend with backend 'home' endpoint connection

**Comment by AugustinMauroy** [comment]
If I may say so, I recommend using Next.js with the RSCs in order to consume the Strapi api. And tailwindcss is very powerful for styling, allowing you to have a wide range of variables without having to be a professional designer.

**Comment by AugustinMauroy** [comment]
And why make the site based on strapi? We could base the content on markdown. Which would make it easy to I18n the content. It would also allow any contributor to modify the content.

**Comment by hanEck** [comment]
Thank you for your interest in the project. We chose strapi because it makes it easy for users to manage content and make structural changes to specific sides. Translations can also be realised in Strapi.

**Comment by AugustinMauroy** [comment]
> Translations can also be realised in Strapi.


oh yeah i had missed this info

**Comment by TheNaman047** [comment]
Is it possible for me to contribute to the project? Are you guys accepting PR?
