### ISSUE TITLE
Invalid URL for Solaris downloads

### ISSUE THREAD

**Issue by schaiba** [vim/website_next_generation#138]
http://wwws.sun.com/software/solaris/freeware/ is not a valid URL and Solaris is now Oracle Solaris.

**Comment by chrisbra** [comment]
where did you see the wrong download link?

**Comment by schaiba** [comment]
on vim.org . I understand that this repo is for the new, revamped website, I just wanted to make sure the download link won't get copied to the new site.

**Comment by chrisbra** [comment]
So this one: https://www.vim.org/download.php

You should have mentioned that. I'll take it out, unless I find another download URL for Solaris where one can download Vim.

**Comment by schaiba** [comment]
You're right, I should've said so from the beginning. Thanks.

**Comment by chrisbra** [comment]
Fixed.
